 # Pandas - cvičení

## Příprava cvičení

 - pro potřeby cvičení si spusť následující kód:

In [1]:
!pip install faker

Collecting faker
  Downloading faker-37.0.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: tzdata in /usr/local/lib/python3.11/dist-packages (from faker) (2025.1)
Downloading faker-37.0.0-py3-none-any.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 18.2 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-37.0.0

In [2]:
import pandas as pd
import random
from faker import Faker

fake = Faker("cs_CZ")  # Generátor náhodných dat v češtině
Faker.seed(42)

# Generování 1000 řádků dat
data = []
for i in range(1, 1001):
    jmeno = fake.name()
    vek = random.randint(22, 60)
    mesto = fake.city()
    plat = random.randint(40000, 80000)
    pozice = random.choice(
        ["Analytik", "Manažer", "Konzultant", "Specialista", "Asistent", "Ředitel", "Technik", "Koordinátor",
         "Projektový manažer"])
    oddeleni = random.choice(
        ["IT", "HR", "Prodej", "Marketing", "Podpora", "Stavba", "Administrativa", "Finanční", "Výroba", "Kvalita"])
    telefon = fake.random_number(digits=9, fix_len=True)
    email = fake.email()
    datum_nastupu = fake.date_between(start_date="-8y", end_date="today").strftime("%Y-%m-%d")
    data.append([i, jmeno, vek, mesto, plat, pozice, oddeleni, telefon, email, datum_nastupu])

# Vytvoření DataFrame
columns = ["Osobní číslo", "Jméno", "Věk", "Město", "Plat", "Pozice", "Oddělení", "Telefon", "Email", "Datum nástupu"]
df = pd.DataFrame(data, columns=columns)

# Uložení do CSV
df.to_csv("pracovnici.csv", index=False, encoding="utf-8")
display('Soubor připraven!')

'Soubor připraven!'

## Import Pandas

 - Pandas už sice bude importován, protože jsme ho využili k vytvoření souboru, ale opakování, matka moudrosti, takže ho naimportuj znovu :)

In [ ]:
import pandas as pd

## Načtení souboru

 - pak je potřeba načíst data z CSV souboru, ať s nimi můžeme pracovat

In [5]:
df_prac = pd.read_csv("pracovnici.csv")

 - mrkni se na několik řádků z dat

In [6]:
df_prac.head()

,Osobní číslo,Jméno,Věk,Město,Plat,Pozice,Oddělení,Telefon,Email,Datum nástupu
0,1,Anastázie Vávrová,29,Hulín,73902,Specialista,Administrativa,339670711,vavradusan@example.net,2023-02-11
1,2,Renáta Beránková,46,Chotěboř,60591,Koordinátor,IT,334760738,pokornyantonin@example.net,2018-10-12
2,3,Žofie Matějková,60,Milevsko,68135,Projektový manažer,Marketing,732719211,agatavlckova@example.org,2022-10-09
3,4,Ivan Hrubý,23,Chyše,79567,Projektový manažer,Podpora,199585092,jozef55@example.net,2019-04-21
4,5,Vojtěch Prokop,31,České Budějovice,50088,Asistent,IT,506448196,ruzickovalydie@example.net,2022-02-19

 - koukni na informace o sloupcích

In [7]:
df_prac.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Osobní číslo   1000 non-null   int64
 1   Jméno          1000 non-null   object
 2   Věk            1000 non-null   int64
 3   Město          1000 non-null   object
 4   Plat           1000 non-null   int64
 5   Pozice         1000 non-null   object
 6   Oddělení       1000 non-null   object
 7   Telefon        1000 non-null   int64
 8   Email          1000 non-null   object
 9   Datum nástupu  1000 non-null   object
dtypes: int64(4), object(6)
memory usage: 78.3+ KB

 - koukni na základní statistické údaje

In [8]:
df_prac.describe()

       Osobní číslo          Věk          Plat       Telefon
count   1000.000000  1000.000000   1000.000000  1.000000e+03
mean     500.500000    40.420000  59376.960000  5.569704e+08
std      288.819436    11.166301  11423.831299  2.571703e+08
min        1.000000    22.000000  40010.000000  1.010749e+08
25%      250.750000    30.000000  49494.000000  3.348265e+08
50%      500.500000    40.000000  59052.000000  5.573649e+08
75%      750.250000    50.000000  68828.000000  7.859518e+08
max     1000.000000    60.000000  79957.000000  9.993714e+08

- a dál už podle lektora :)

In [9]:
df_prac.describe(include = "all")

,Osobní číslo,Jméno,Věk,Město,Plat,Pozice,Oddělení,Telefon,Email,Datum nástupu
count,1000.000000,1000,1000.000000,1000,1000.000000,1000,1000,1.000000e+03,1000,1000
unique,NaN,978,NaN,425,NaN,9,10,NaN,994,855
top,NaN,Jiřina Němečková,NaN,Plzeň,NaN,Specialista,Prodej,NaN,dhorakova@example.com,2021-06-17
freq,NaN,2,NaN,7,NaN,120,109,NaN,2,4
mean,500.500000,NaN,40.420000,NaN,59376.960000,NaN,NaN,5.569704e+08,NaN,NaN
std,288.819436,NaN,11.166301,NaN,11423.831299,NaN,NaN,2.571703e+08,NaN,NaN
min,1.000000,NaN,22.000000,NaN,40010.000000,NaN,NaN,1.010749e+08,NaN,NaN
25%,250.750000,NaN,30.000000,NaN,49494.000000,NaN,NaN,3.348265e+08,NaN,NaN
50%,500.500000,NaN,40.000000,NaN,59052.000000,NaN,NaN,5.573649e+08,NaN,NaN
75%,750.250000,NaN,50.000000,NaN,68828.000000,NaN,NaN,7.859518e+08,NaN,NaN
max,1000.000000,NaN,60.000000,NaN,79957.000000,NaN,NaN,9.993714e+08,NaN,NaN

In [10]:
df_prac["Věk"].describe(include = "all")

count    1000.000000
mean       40.420000
std        11.166301
min        22.000000
25%        30.000000
50%        40.000000
75%        50.000000
max        60.000000
Name: Věk, dtype: float64

In [12]:
df_prac["Město"].value_counts

<bound method IndexOpsMixin.value_counts of 0                     Hulín
1                  Chotěboř
2                  Milevsko
3                     Chyše
4          České Budějovice
               ...
995                   Chyše
996     Hradec nad Moravicí
997                Protivín
998                 Rýmařov
999    Rožmberk nad Vltavou
Name: Město, Length: 1000, dtype: object>

In [13]:
df_prac.describe()

       Osobní číslo          Věk          Plat       Telefon
count   1000.000000  1000.000000   1000.000000  1.000000e+03
mean     500.500000    40.420000  59376.960000  5.569704e+08
std      288.819436    11.166301  11423.831299  2.571703e+08
min        1.000000    22.000000  40010.000000  1.010749e+08
25%      250.750000    30.000000  49494.000000  3.348265e+08
50%      500.500000    40.000000  59052.000000  5.573649e+08
75%      750.250000    50.000000  68828.000000  7.859518e+08
max     1000.000000    60.000000  79957.000000  9.993714e+08

In [17]:
df_prac["Osobní číslo"] = df_prac["Osobní číslo"].astype("object")

In [18]:
df_prac.describe()

               Věk          Plat       Telefon
count  1000.000000   1000.000000  1.000000e+03
mean     40.420000  59376.960000  5.569704e+08
std      11.166301  11423.831299  2.571703e+08
min      22.000000  40010.000000  1.010749e+08
25%      30.000000  49494.000000  3.348265e+08
50%      40.000000  59052.000000  5.573649e+08
75%      50.000000  68828.000000  7.859518e+08
max      60.000000  79957.000000  9.993714e+08

In [19]:
df_prac["Telefon"] = df_prac["Telefon"].astype("object")

In [20]:
df_prac.describe()

               Věk          Plat
count  1000.000000   1000.000000
mean     40.420000  59376.960000
std      11.166301  11423.831299
min      22.000000  40010.000000
25%      30.000000  49494.000000
50%      40.000000  59052.000000
75%      50.000000  68828.000000
max      60.000000  79957.000000

In [21]:
df_prac.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Osobní číslo   1000 non-null   object
 1   Jméno          1000 non-null   object
 2   Věk            1000 non-null   int64
 3   Město          1000 non-null   object
 4   Plat           1000 non-null   int64
 5   Pozice         1000 non-null   object
 6   Oddělení       1000 non-null   object
 7   Telefon        1000 non-null   object
 8   Email          1000 non-null   object
 9   Datum nástupu  1000 non-null   object
dtypes: int64(2), object(8)
memory usage: 78.3+ KB

In [24]:
df_prac[(df_prac["Věk"] > 40) & (df_prac["Plat"] > 50000)]

,Osobní číslo,Jméno,Věk,Město,Plat,Pozice,Oddělení,Telefon,Email,Datum nástupu
1,2,Renáta Beránková,46,Chotěboř,60591,Koordinátor,IT,334760738,pokornyantonin@example.net,2018-10-12
2,3,Žofie Matějková,60,Milevsko,68135,Projektový manažer,Marketing,732719211,agatavlckova@example.org,2022-10-09
5,6,Jarmila Urbanová,52,Brtnice,53873,Asistent,Finanční,810026086,zemanmilan@example.org,2024-01-12
7,8,Ctirad Strnad,41,Náměšť nad Oslavou,57241,Specialista,Podpora,882893941,hajekvratislav@example.com,2019-05-07
12,13,Alena Tichá,55,Sedlec-Prčice,54217,Manažer,Finanční,676567501,miloslavadolezalova@example.com,2020-08-31
...,...,...,...,...,...,...,...,...,...,...
990,991,Olga Tichá,41,Bílovec,67142,Ředitel,Marketing,254105962,matouskovaklara@example.com,2024-06-17
991,992,Dorota Valentová,57,Starý Plzenec,57523,Specialista,Finanční,905783320,stejskalovadorota@example.com,2020-04-05
994,995,Hedvika Králová,42,Moravský Krumlov,67695,Analytik,Marketing,265907416,blahamatous@example.net,2021-07-15
998,999,Pavel Stejskal,51,Rýmařov,72498,Technik,IT,556602863,svecmiroslav@example.net,2023-09-23
999,1000,Dušan Kašpar,44,Rožmberk nad Vltavou,63856,Manažer,Výroba,496331524,danabartosova@example.org,2023-05-30

In [25]:
df_prac.columns

Index(['Osobní číslo', 'Jméno', 'Věk', 'Město', 'Plat', 'Pozice', 'Oddělení',
       'Telefon', 'Email', 'Datum nástupu'],
      dtype='object')

In [ ]:
df_prac[(df_prac["Věk"] > 40) & (df_prac["Plat"] > 50000)].describe(include all)

In [ ]:
df_prac[(df_prac["Věk"] > 40) & (df_prac["Plat"] > 50000)]["Město"].value_counts()

In [26]:
df_vyber = df_prac[(df_prac["Věk"] > 40) & (df_prac["Plat"] > 50000)]
df_vyber["Město"].value_counts()

Město
Kasejovice          6
Rájec-Jestřebí      5
Česká Skalice       4
Luby                4
Starý Plzenec       4
                   ..
Volyně              1
Studénka            1
Trhové Sviny        1
Vamberk             1
Moravský Krumlov    1
Name: count, Length: 249, dtype: int64

In [27]:
df_prac.head()

,Osobní číslo,Jméno,Věk,Město,Plat,Pozice,Oddělení,Telefon,Email,Datum nástupu
0,1,Anastázie Vávrová,29,Hulín,73902,Specialista,Administrativa,339670711,vavradusan@example.net,2023-02-11
1,2,Renáta Beránková,46,Chotěboř,60591,Koordinátor,IT,334760738,pokornyantonin@example.net,2018-10-12
2,3,Žofie Matějková,60,Milevsko,68135,Projektový manažer,Marketing,732719211,agatavlckova@example.org,2022-10-09
3,4,Ivan Hrubý,23,Chyše,79567,Projektový manažer,Podpora,199585092,jozef55@example.net,2019-04-21
4,5,Vojtěch Prokop,31,České Budějovice,50088,Asistent,IT,506448196,ruzickovalydie@example.net,2022-02-19

In [33]:
df_prac.groupby("Pozice", observed=True)["Plat"].mean().reset_index()

               Pozice          Plat
0            Analytik  60445.580000
1            Asistent  58483.170213
2          Konzultant  58270.673077
3         Koordinátor  59077.504274
4             Manažer  59767.093220
5  Projektový manažer  59532.947368
6         Specialista  59653.233333
7             Technik  58926.016807
8             Ředitel  60113.236842

In [34]:
df_prac.groupby(["Pozice", "Město"], observed=True).agg({"Plat": ["mean", "max", "min"]})

                                   Plat
                                   mean    max    min
Pozice   Město
Analytik Adamov                 57884.0  57884  57884
         Andělská Hora          63864.0  63864  63864
         Bavorov                77754.0  77754  77754
         Benešov nad Ploučnicí  58378.0  58378  58378
         Bor                    66239.0  66239  66239
...                                 ...    ...    ...
Ředitel  Žamberk                72303.0  72303  72303
         Žandov                 76553.0  76553  76553
         Žebrák                 63374.0  63374  63374
         Žirovnice              75506.0  75506  75506
         Žlutice                72083.0  72083  72083

[879 rows x 3 columns]